export const MOCK_USERS = [
  {
    id: 1,
    name: 'Sarah Chen',
    email: 'sarah.chen@company.com',
    role: 'Admin',
    status: 'active',
    joinDate: '2024-01-15',
    department: 'Engineering',
    lastLogin: '2024-11-18 14:30',
    avatar: 'SC',
  },
  {
    id: 2,
    name: 'Mike Johnson',
    email: 'mike.johnson@company.com',
    role: 'Senior Editor',
    status: 'active',
    joinDate: '2024-02-20',
    department: 'Content',
    lastLogin: '2024-11-18 10:15',
    avatar: 'MJ',
  },
  {
    id: 3,
    name: 'Emily Davis',
    email: 'emily.davis@company.com',
    role: 'Viewer',
    status: 'inactive',
    joinDate: '2024-03-10',
    department: 'Marketing',
    lastLogin: '2024-11-15 09:45',
    avatar: 'ED',
  },
  {
    id: 4,
    name: 'Alex Smith',
    email: 'alex.smith@company.com',
    role: 'Editor',
    status: 'active',
    joinDate: '2024-01-30',
    department: 'Product',
    lastLogin: '2024-11-18 13:20',
    avatar: 'AS',
  },
  {
    id: 5,
    name: 'Jessica Liu',
    email: 'jessica.liu@company.com',
    role: 'Admin',
    status: 'active',
    joinDate: '2024-02-14',
    department: 'Engineering',
    lastLogin: '2024-11-18 15:45',
    avatar: 'JL',
  },
  {
    id: 6,
    name: 'David Martinez',
    email: 'david.martinez@company.com',
    role: 'Editor',
    status: 'active',
    joinDate: '2024-04-05',
    department: 'Design',
    lastLogin: '2024-11-18 11:30',
    avatar: 'DM',
  },
  {
    id: 7,
    name: 'Lisa Wong',
    email: 'lisa.wong@company.com',
    role: 'Viewer',
    status: 'active',
    joinDate: '2024-05-12',
    department: 'Finance',
    lastLogin: '2024-11-17 16:20',
    avatar: 'LW',
  },
  {
    id: 8,
    name: 'James Taylor',
    email: 'james.taylor@company.com',
    role: 'Senior Editor',
    status: 'inactive',
    joinDate: '2024-03-28',
    department: 'Operations',
    lastLogin: '2024-11-10 08:00',
    avatar: 'JT',
  },
]

export type User = typeof MOCK_USERS[0]
